package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"io"
	"log"
	"net/http"
	"os"
	"regexp"
	"strings"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

const openAIChatCompletionsPath = "/v1/chat/completions"

// Prometheus metric definitions (counters, histograms, gauges)
var (
	promptTokens = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "ollama_prompt_tokens_total",
			Help: "Total number of prompt tokens sent to the model",
		},
		[]string{"model"},
	)
	generatedTokens = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "ollama_generated_tokens_total",
			Help: "Total number of tokens generated by the model",
		},
		[]string{"model"},
	)
	requestDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name: "ollama_request_duration_seconds",
			Help: "Duration of Ollama requests in seconds",
			// Buckets for 0.1s to 60s
			Buckets: []float64{0.1, 0.5, 1, 2, 5, 10, 30, 60},
		},
		[]string{"endpoint", "model"},
	)
	timePerToken = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "ollama_time_per_token_seconds",
			Help:    "Time per generated token (seconds per token)",
			Buckets: []float64{0.01, 0.05, 0.1, 0.2, 0.5, 1, 2},
		},
		[]string{"model"},
	)
	loadedModelsGauge = prometheus.NewGauge(
		prometheus.GaugeOpts{
			Name: "ollama_loaded_models",
			Help: "Number of models currently loaded in memory in Ollama",
		},
	)
	loadedModelInfo = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "ollama_model_loaded",
			Help: "Indicator (1/0) if a model is loaded in memory",
		},
		[]string{"model"},
	)
	modelRAMUsage = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "ollama_model_ram_mb",
			Help: "RAM usage in megabytes for each loaded model",
		},
		[]string{"model"},
	)
)

func init() {
	// Register metrics with Prometheus default registry.
	prometheus.MustRegister(promptTokens, generatedTokens, requestDuration, timePerToken, loadedModelsGauge, loadedModelInfo, modelRAMUsage)
}

// Structs to parse JSON responses from Ollama.
type generateResponse struct {
	Model              string      `json:"model"`
	Done               *bool       `json:"done,omitempty"`
	Response           string      `json:"response,omitempty"`
	PromptEvalCount    *int        `json:"prompt_eval_count,omitempty"`
	EvalCount          *int        `json:"eval_count,omitempty"`
	TotalDuration      *int64      `json:"total_duration,omitempty"`
	EvalDuration       *int64      `json:"eval_duration,omitempty"`
	PromptEvalDuration *int64      `json:"prompt_eval_duration,omitempty"`
	DoneReason         interface{} `json:"done_reason,omitempty"`
}

// OpenAI-compatible chat responses contain usage in the final JSON response
// or in a final SSE data event when stream_options.include_usage is enabled.
type openAIUsage struct {
	PromptTokens     int `json:"prompt_tokens"`
	CompletionTokens int `json:"completion_tokens"`
	TotalTokens      int `json:"total_tokens"`
}

type openAIResponse struct {
	Model   string        `json:"model"`
	Usage   *openAIUsage  `json:"usage,omitempty"`
	Choices []interface{} `json:"choices,omitempty"`
}

type psResponse struct {
	Models []struct {
		Name      string `json:"name"`
		ID        string `json:"id"`
		Size      int64  `json:"size"` // Size in bytes
		Processor string `json:"processor"`
		Until     string `json:"until"`
	} `json:"models"`
}

type modelsResponse struct {
	Models []struct {
		Name    string `json:"name"`
		Model   string `json:"model"`
		Size    int64  `json:"size"`
		Digest  string `json:"digest"`
		Details struct {
			ParentModel       string   `json:"parent_model"`
			Format            string   `json:"format"`
			Family            string   `json:"family"`
			Families          []string `json:"families"`
			ParameterSize     string   `json:"parameter_size"`
			QuantizationLevel string   `json:"quantization_level"`
		} `json:"details"`
		ExpiresAt string `json:"expires_at"`
		SizeVRAM  int64  `json:"size_vram"`
	} `json:"models"`
}

var upstreamClient = &http.Client{
	// No global timeout; model inference may take a long time.
	Timeout: 0,
}

// fixDoneReason processes JSON data to handle the done_reason field that might
// be a number or string.
func fixDoneReason(data []byte) []byte {
	re := regexp.MustCompile(`"done_reason":(\d+)`)
	return re.ReplaceAll(data, []byte(`"done_reason":"$1"`))
}

// ensureModelTag adds ":latest" to model names that don't have a tag.
func ensureModelTag(modelName string) string {
	if modelName == "" {
		return modelName
	}
	if !strings.Contains(modelName, ":") {
		return modelName + ":latest"
	}
	return modelName
}

// parseOpenAIChatCompletionsUsage extracts the model and final usage values
// from either a non-streaming JSON response or OpenAI-style SSE data lines.
func parseOpenAIChatCompletionsUsage(data []byte) (string, int, int) {
	var model string
	var promptCount, generatedCount int

	parse := func(payload []byte) {
		var response openAIResponse
		if err := json.Unmarshal(payload, &response); err != nil {
			return
		}
		if response.Model != "" {
			model = ensureModelTag(response.Model)
		}
		if response.Usage != nil {
			promptCount = response.Usage.PromptTokens
			generatedCount = response.Usage.CompletionTokens
		}
	}

	// Non-streaming responses are a single JSON document, including when they
	// contain whitespace or newlines.
	if json.Valid(data) {
		parse(data)
		return model, promptCount, generatedCount
	}

	// Streaming responses are SSE. Ollama emits one JSON object per data line.
	for _, line := range bytes.Split(data, []byte{'\n'}) {
		line = bytes.TrimSpace(line)
		if !bytes.HasPrefix(line, []byte("data:")) {
			continue
		}
		payload := bytes.TrimSpace(bytes.TrimPrefix(line, []byte("data:")))
		if bytes.Equal(payload, []byte("[DONE]")) {
			continue
		}
		parse(payload)
	}

	return model, promptCount, generatedCount
}

// prepareOpenAIChatRequest asks Ollama for the final usage SSE event when the
// client requested streaming but did not already request that event. The
// second return value tells the response path to consume the added usage-only
// event instead of exposing it to a client that did not ask for it.
func prepareOpenAIChatRequest(data []byte) ([]byte, bool) {
	var request map[string]json.RawMessage
	if err := json.Unmarshal(data, &request); err != nil {
		return data, false
	}

	var stream bool
	if raw, ok := request["stream"]; !ok || json.Unmarshal(raw, &stream) != nil || !stream {
		return data, false
	}

	options := make(map[string]json.RawMessage)
	if raw, ok := request["stream_options"]; ok {
		var decodedOptions map[string]json.RawMessage
		if err := json.Unmarshal(raw, &decodedOptions); err != nil {
			// Preserve the client's invalid request rather than changing its
			// validation behavior just to collect metrics.
			return data, false
		}
		if decodedOptions != nil {
			options = decodedOptions
		}
	}

	var includeUsage bool
	if raw, ok := options["include_usage"]; ok {
		if json.Unmarshal(raw, &includeUsage) == nil && includeUsage {
			return data, false
		}
	}

	options["include_usage"] = json.RawMessage("true")
	encodedOptions, err := json.Marshal(options)
	if err != nil {
		return data, false
	}
	request["stream_options"] = encodedOptions

	encodedRequest, err := json.Marshal(request)
	if err != nil {
		return data, false
	}
	return encodedRequest, true
}

// parseOpenAIEvent returns the model and usage carried by one complete SSE
// event. It also identifies Ollama's usage-only terminal event, which is the
// event added by prepareOpenAIChatRequest for clients that did not request it.
func parseOpenAIEvent(event []byte) (string, int, int, bool) {
	var model string
	var promptCount, generatedCount int
	usageOnly := false
	for _, line := range bytes.Split(event, []byte{'\n'}) {
		line = bytes.TrimSpace(line)
		if !bytes.HasPrefix(line, []byte("data:")) {
			continue
		}
		payload := bytes.TrimSpace(bytes.TrimPrefix(line, []byte("data:")))
		if bytes.Equal(payload, []byte("[DONE]")) {
			continue
		}

		var response openAIResponse
		if err := json.Unmarshal(payload, &response); err != nil {
			continue
		}
		if response.Model != "" {
			model = ensureModelTag(response.Model)
		}
		if response.Usage != nil {
			promptCount = response.Usage.PromptTokens
			generatedCount = response.Usage.CompletionTokens
			usageOnly = len(response.Choices) == 0
		}
	}
	return model, promptCount, generatedCount, usageOnly
}

func isSSEBlankLine(line []byte) bool {
	return len(bytes.TrimSpace(line)) == 0
}

// streamOpenAIChatResponse forwards complete SSE events as soon as they are
// available while retaining only the usage values needed for metrics. This
// preserves streaming latency instead of buffering the whole model response.
func streamOpenAIChatResponse(w http.ResponseWriter, body io.Reader, stripInjectedUsage bool) (string, int, int) {
	reader := bufio.NewReader(body)
	flusher, _ := w.(http.Flusher)
	var event bytes.Buffer
	var model string
	var promptCount, generatedCount int

	writeEvent := func(data []byte) bool {
		eventModel, eventPrompt, eventGenerated, usageOnly := parseOpenAIEvent(data)
		if eventModel != "" {
			model = eventModel
		}
		if eventPrompt != 0 || eventGenerated != 0 {
			promptCount = eventPrompt
			generatedCount = eventGenerated
		}
		if stripInjectedUsage && usageOnly {
			return true
		}
		if _, err := w.Write(data); err != nil {
			log.Printf("WARNING: client write error: %v", err)
			return false
		}
		if flusher != nil {
			flusher.Flush()
		}
		return true
	}

	for {
		line, readErr := reader.ReadBytes('\n')
		if len(line) > 0 {
			event.Write(line)
			if isSSEBlankLine(line) {
				if !writeEvent(event.Bytes()) {
					break
				}
				event.Reset()
			}
		}
		if readErr != nil {
			if readErr != io.EOF {
				log.Printf("ERROR reading upstream: %v", readErr)
			}
			break
		}
	}

	// Be tolerant of an upstream that closes an SSE stream without the final
	// blank line. Valid Ollama streams use the branch above.
	if event.Len() > 0 {
		writeEvent(event.Bytes())
	}

	return model, promptCount, generatedCount
}

func requestModel(body []byte) string {
	var request struct {
		Model string `json:"model"`
	}
	if json.Unmarshal(body, &request) == nil {
		return ensureModelTag(request.Model)
	}
	return ""
}

func updateRequestMetrics(start time.Time, endpoint, modelName string, promptCount, generatedCount int, evalDurationNs int64) {
	if modelName == "" {
		return
	}
	if promptCount > 0 {
		promptTokens.WithLabelValues(modelName).Add(float64(promptCount))
	}
	if generatedCount > 0 {
		generatedTokens.WithLabelValues(modelName).Add(float64(generatedCount))
	}
	requestDuration.WithLabelValues(endpoint, modelName).Observe(time.Since(start).Seconds())
	if generatedCount > 0 && evalDurationNs > 0 {
		secondsPerToken := float64(evalDurationNs) / 1e9 / float64(generatedCount)
		timePerToken.WithLabelValues(modelName).Observe(secondsPerToken)
	}
}

func main() {
	// Configure upstream Ollama host and local port from environment.
	upstreamAddr := os.Getenv("OLLAMA_HOST")
	if upstreamAddr == "" {
		upstreamAddr = "http://localhost:11434"
	}
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	log.Printf("Starting Ollama proxy sidecar, forwarding to %s", upstreamAddr)

	// Initialize the loaded models gauge at startup when the backend is ready.
	if resp, err := upstreamClient.Get(upstreamAddr + "/api/ps"); err == nil {
		var ps psResponse
		data, _ := io.ReadAll(resp.Body)
		resp.Body.Close()
		if jsonErr := json.Unmarshal(data, &ps); jsonErr == nil {
			loadedModelsGauge.Set(float64(len(ps.Models)))
			loadedModelInfo.Reset()
			for _, m := range ps.Models {
				loadedModelInfo.WithLabelValues(ensureModelTag(m.Name)).Set(1)
			}
		}
	}

	mux := http.NewServeMux()

	// Refresh model data before serving metrics.
	mux.HandleFunc("/metrics", func(w http.ResponseWriter, r *http.Request) {
		if resp, err := upstreamClient.Get(upstreamAddr + "/api/ps"); err == nil {
			var ps psResponse
			data, _ := io.ReadAll(resp.Body)
			resp.Body.Close()
			if jsonErr := json.Unmarshal(data, &ps); jsonErr == nil {
				loadedModelsGauge.Set(float64(len(ps.Models)))
				loadedModelInfo.Reset()
				modelRAMUsage.Reset()
				for _, m := range ps.Models {
					modelName := ensureModelTag(m.Name)
					loadedModelInfo.WithLabelValues(modelName).Set(1)
					ramMB := float64(m.Size) / (1024 * 1024)
					modelRAMUsage.WithLabelValues(modelName).Set(ramMB)
				}
				log.Printf("Refreshed metrics data: %d models loaded", len(ps.Models))
			} else {
				log.Printf("ERROR parsing /api/ps response during metrics refresh: %v", jsonErr)
			}
		} else {
			log.Printf("ERROR refreshing model metrics: %v", err)
		}
		promhttp.Handler().ServeHTTP(w, r)
	})

	// All other paths are transparent proxy requests, with metrics extraction
	// added only for native generation and OpenAI-compatible chat completions.
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()
		if r.URL.Path == "/metrics" {
			promhttp.Handler().ServeHTTP(w, r)
			return
		}

		var bodyBytes []byte
		if r.Body != nil {
			bodyBytes, _ = io.ReadAll(r.Body)
			r.Body.Close()
		}
		requestedModel := requestModel(bodyBytes)
		stripInjectedUsage := false
		if r.URL.Path == openAIChatCompletionsPath {
			bodyBytes, stripInjectedUsage = prepareOpenAIChatRequest(bodyBytes)
		}

		targetURL := upstreamAddr + r.URL.Path
		if r.URL.RawQuery != "" {
			targetURL += "?" + r.URL.RawQuery
		}
		reqUp, err := http.NewRequest(r.Method, targetURL, bytes.NewReader(bodyBytes))
		if err != nil {
			http.Error(w, "Bad request", http.StatusInternalServerError)
			log.Printf("ERROR creating upstream request: %v", err)
			return
		}
		for name, vals := range r.Header {
			if name == "Host" {
				continue
			}
			for _, v := range vals {
				reqUp.Header.Add(name, v)
			}
		}
		if reqUp.Header.Get("Content-Type") == "" && len(bodyBytes) > 0 {
			reqUp.Header.Set("Content-Type", "application/json")
		}

		respUp, err := upstreamClient.Do(reqUp)
		if err != nil {
			http.Error(w, "Upstream error", http.StatusBadGateway)
			log.Printf("ERROR forwarding to upstream: %v", err)
			return
		}
		defer respUp.Body.Close()

		for name, vals := range respUp.Header {
			switch strings.ToLower(name) {
			case "transfer-encoding", "content-length":
				continue
			}
			for _, v := range vals {
				w.Header().Add(name, v)
			}
		}
		w.WriteHeader(respUp.StatusCode)

		var modelName string
		var promptCount, generatedCount int
		var evalDurationNs int64

		switch {
		case r.URL.Path == openAIChatCompletionsPath:
			if strings.Contains(respUp.Header.Get("Content-Type"), "text/event-stream") {
				modelName, promptCount, generatedCount = streamOpenAIChatResponse(w, respUp.Body, stripInjectedUsage)
			} else {
				bodyData, _ := io.ReadAll(respUp.Body)
				_, _ = w.Write(bodyData)
				modelName, promptCount, generatedCount = parseOpenAIChatCompletionsUsage(bodyData)
			}
			if modelName == "" {
				modelName = requestedModel
			}

		case r.URL.Path == "/api/generate" || r.URL.Path == "/api/chat":
			// Handle streaming JSON response for native generate/chat. This is
			// intentionally kept compatible with the original proxy behavior.
			var buf bytes.Buffer
			streamWriter := io.MultiWriter(w, &buf)
			flusher, _ := w.(http.Flusher)
			chunk := make([]byte, 1024)
			for {
				n, readErr := respUp.Body.Read(chunk)
				if n > 0 {
					if _, writeErr := streamWriter.Write(chunk[:n]); writeErr != nil {
						log.Printf("WARNING: client write error: %v", writeErr)
						break
					}
					if flusher != nil {
						flusher.Flush()
					}
				}
				if readErr != nil {
					if readErr != io.EOF {
						log.Printf("ERROR reading upstream: %v", readErr)
					}
					break
				}
			}

			bufData := fixDoneReason(buf.Bytes())
			var modelsResp modelsResponse
			if err := json.Unmarshal(bufData, &modelsResp); err == nil && len(modelsResp.Models) > 0 {
				for _, model := range modelsResp.Models {
					modelName = ensureModelTag(model.Model)
					modelRAMUsage.WithLabelValues(modelName).Set(float64(model.SizeVRAM) / (1024 * 1024))
				}
				log.Printf("Received models list response with %d models", len(modelsResp.Models))
			} else {
				for _, line := range bytes.Split(bufData, []byte{'\n'}) {
					if len(line) == 0 {
						continue
					}
					var res generateResponse
					if err := json.Unmarshal(line, &res); err != nil {
						log.Printf("WARNING: Failed to parse JSON: %v", err)
						continue
					}
					if res.Model != "" {
						modelName = ensureModelTag(res.Model)
					}
					if res.Done != nil && *res.Done {
						if res.PromptEvalCount != nil {
							promptCount = *res.PromptEvalCount
						}
						if res.EvalCount != nil {
							generatedCount = *res.EvalCount
						}
						if res.EvalDuration != nil {
							evalDurationNs = *res.EvalDuration
						}
					}
				}
			}

		case r.URL.Path == "/api/ps":
			bodyData, _ := io.ReadAll(respUp.Body)
			_, _ = w.Write(bodyData)
			var ps psResponse
			if err := json.Unmarshal(bodyData, &ps); err == nil {
				loadedModelsGauge.Set(float64(len(ps.Models)))
				loadedModelInfo.Reset()
				modelRAMUsage.Reset()
				for _, m := range ps.Models {
					modelName := ensureModelTag(m.Name)
					loadedModelInfo.WithLabelValues(modelName).Set(1)
					ramMB := float64(m.Size) / (1024 * 1024)
					modelRAMUsage.WithLabelValues(modelName).Set(ramMB)
					log.Printf("Model %s RAM usage: %.2f MB", modelName, ramMB)
				}
			} else {
				log.Printf("ERROR parsing /api/ps response: %v", err)
			}
			return

		default:
			// Other endpoints remain pass-through. Preserve the original request
			// body and response bytes without attempting to interpret them.
			_, _ = io.Copy(w, respUp.Body)
			modelName = requestedModel
		}

		endpoint := strings.TrimPrefix(r.URL.Path, "/api/")
		if endpoint == "" {
			endpoint = r.URL.Path
		}
		updateRequestMetrics(start, endpoint, modelName, promptCount, generatedCount, evalDurationNs)

		duration := time.Since(start).Seconds()
		if modelName != "" && (promptCount > 0 || generatedCount > 0) {
			log.Printf("%s %s -> model=%s prompt_tokens=%d generated_tokens=%d duration=%.2fs",
				r.Method, r.URL.Path, modelName, promptCount, generatedCount, duration)
		} else {
			log.Printf("%s %s -> status=%d duration=%.2fs", r.Method, r.URL.Path, respUp.StatusCode, duration)
		}
	})

	listenAddr := ":" + port
	log.Printf("Listening on %s", listenAddr)
	log.Fatal(http.ListenAndServe(listenAddr, mux))
}
